"""delete ho

Revision ID: 84de2d58d6d6
Revises: 3adb2724fdcb
Create Date: 2024-10-06 21:50:37.651447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84de2d58d6d6'
down_revision = '3adb2724fdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ho')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ho', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
